version: '3.9'
services:
  react-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-container
    ports:
      - "8082:80"    
    volumes:
      - ./build/:/usr/share/nginx/html/
      