# apiVersion: v1
# kind: Service
# metadata:
#   name: react-app-service
#   namespace: react-app-namespace
# spec:
#   selector:
#     app: react-app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react-frontend
    version: blue   # change to green
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

